name: MoneyPouch
# This will be replaced with the property "release.version" in pom.xml upon build.
version: %PLUGIN_VERSION%
main: com.leonardobishop.moneypouch.MoneyPouch
authors: [ LMBishop, Wertik1206 ]
softdepend: [ Vault ]

commands:
  moneypouch:
    description: Main command for MoneyPouch
    usage: /moneypouch
    permission: moneypouch.admin
    aliases: [ mp ]

permissions:
  moneypouch.admin:
    description: Permission for the base command
