name: MoneyPouch
# This will be replaced with the property "release.version" in pom.xml upon build.
version: %PLUGIN_VERSION%
api-version: 1.16
main: com.leonardobishop.moneypouch.PouchPlugin
authors: [ LMBishop, Wertik1206 ]
softdepend: [ Vault ]

commands:
  moneypouch:
    description: Main command for MoneyPouch
    usage: /moneypouch
    permission: moneypouch.admin
    aliases: [ mp ]

permissions:
  moneypouch.admin:
    description: Permission for the base command
